### ISSUE TITLE
Questions about codes...

### ISSUE THREAD

**Issue by jgim06932** [anugrahjo/atomics_lite#1]
Hello.

I am currently an undergraduate student and I will get into graduate school as a master's program next semester in South Korea. I am interested in the structural optimization including topology optimization, and I recently ran the 99-line Matlab topology optimization code. The optimal design results were very interesting.

After this, while searching for a Python-based topology optimization code, I accidentally found the code (atomics?) using FEniCS and OpenMDAO. This was very impressive to me. So I have tried to get started a code by following your documentation, and from this I have a few questions: Although this may be a stupid question...

Q1. I ran your cantilever beam code, but the quadrilateral mesh for the rectangular domain is not created and an error occurs. For a Square domain, it seems to be created without error. Is there something I'm doing wrong or missing something during the installation or running process? For your information, I installed the latest 2019.01 version of FEniCS. I looked it up and until recently, FEniCS only seemed to support triangular meshes, is that correct?

https://github.com/anugrahjo/atomics_lite/blob/5efaafa3057e07258c767d7d67dd1ab65f69caa6/atomics_lite/examples/case_1_cantilever_beam_opts/run_cantilever_beam.py#L19

Q2. What is the OpenMDAO and why use it? Is the OpenMDAO necessary for topological optimization?

I know you are busy, but it would be very grateful if you could reply.
If it is hard to give the answers here, it would be also OK to reply to my email address, jgim06932@gmail.com

**Comment by anugrahjo** [comment]
Hello,

This repository (atomics_lite) is based on the 'ATOMiCS' package and was not intended for deployment. Moreover, the questions here are more relevant to the original 'ATOMiCS' package and since they were answered by the main developer [here](https://github.com/LSDOlab/atomics/issues/24) , I am closing this issue.
